jobs:
  - name: rituraj-1-1
    type: manifest
    steps:
      - IN: box-nginx-2
        branch: master
      - IN: sample_nodejs_runCI
        
 
  - name: sample_nodejs_runCI
    type: runCI
    steps:
      - IN: rituraj-1-1
        branch: rc
