triggers:
  - name: trigger-dv-man-1-1-master
    type: trigger
    version:
      counter: 64412345
      
  - name: tr1-1-master
    type: trigger
    version:
      counter: 24412345
      
      

